---
title: "Text Mining with R - Julia Silge and David Robinson"
author: "Monika Biernat"
date: "November 14, 2018"
output:
  html_document:
    theme: cerulean
    toc: true
    toc_float: true
    toc_collapsed: false
---


```{r, echo=FALSE, error=FALSE, message=FALSE, warning=FALSE}
library(tidytext)
library(ggplot2)
library(dplyr)
library(googlesheets)
library(tidyr)
library(corrplot)
library(readr)
library(Hmisc)
library(stringr)
library(knitr)
library(car)


opts_chunk$set(message=FALSE, warning=FALSE)

```




Examples from book "Text Mining with R - Julia Silge and David Robinson" 

https://www.tidytextmining.com/preface.html


# 1.  The tidy text format

## The unnest_tokens function
```{r}
text <- c("Because I could not stop for Death -",
          "He kindly stopped for me -",
          "The Carriage held but just Ourselves -",
          "and Immortality")

text
```

__Change to dataframe__
```{r}
text_df <- data_frame(line = 1:4, text = text)
text_df
str(text_df)
```
__Break the text into token__
```{r}
library(tidytext)

text_df %>%
  unnest_tokens(word, text)

text_df
```

__Polish sentence__
```{r}
textpol <- c("Gdyby kózka nie skakała, -",
             "To by smutne życie, - ",
             "miała.")

 textpol_df <- data_frame(line=1:3, text = textpol)
 
 textpol_df %>%
  unnest_tokens(word, text)
```

## Tidying the works of Jane Austen
```{r}
library(janeaustenr)
library(dplyr)
library(stringr)

str(austen_books())
austen_books()[600:800,]

original_books <- austen_books() %>%
  group_by(book) %>%
  mutate(linenumber = row_number(),
          chapter = cumsum(str_detect(text, regex("^chapter [\\divxlc]",
           ignore_case = TRUE)))) %>%
  ungroup()

original_books


# cumsum - cumulative sums
```
__ one-token-per-row__
```{r}
library(tidytext)
tidy_books <- original_books %>%
  unnest_tokens(word, text)

tidy_books
```

__remove stop words__
```{r}
stop_words
data(stop_words)

tidy_books <- tidy_books %>%
  anti_join(stop_words)

# anti_join -  return all rows from x where there are not matching values in y, keeping just columns from x
```

__count words__
```{r}
tidy_books %>%
  count(word, sort = TRUE) 


tidy_books %>%
  count(word, sort = TRUE) %>%
  filter(n > 600) %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n)) +
  geom_col() +
  xlab(NULL) +
  coord_flip()


```


##  Word frequencies -Gutenbergr
```{r}
library(gutenbergr)
#  H.G. Wells -  The Time Machine, The War of the Worlds, The Invisible Man, and The Island of Doctor Moreau.
hgwells <- gutenberg_download(c(35, 36, 5230, 159))

tidy_hgwells <- hgwells %>%
  unnest_tokens(word, text) %>%
  anti_join(stop_words)

tidy_hgwells %>%
  count(word, sort = TRUE)
 
#  Brontë sisters -  Jane Eyre, Wuthering Heights, The Tenant of Wildfell Hall, Villette, and Agnes Grey
bronte <- gutenberg_download(c(1260, 768, 969, 9182, 767))

tidy_bronte <- bronte %>%
  unnest_tokens(word, text) %>%
  anti_join(stop_words)


tidy_bronte %>%
  count(word, sort = TRUE)


frequency <- bind_rows(mutate(tidy_bronte, author = "Brontë Sisters"),
                       mutate(tidy_hgwells, author = "H.G. Wells"), 
                       mutate(tidy_books, author = "Jane Austen")) %>% 
  mutate(word = str_extract(word, "[a-z']+")) %>%
  count(author, word) %>%
  group_by(author) %>%
  mutate(proportion = n / sum(n)) %>% 
  select(-n) %>% 
  spread(author, proportion) %>% 
  gather(author, proportion, `Brontë Sisters`:`H.G. Wells`)



frequency
table(frequency$author)


library(scales)
# expect a warning about rows with missing values being removed
ggplot(frequency, aes(x = proportion, y = `Jane Austen`, color = abs(`Jane Austen` - proportion))) +
  geom_abline(color = "gray40", lty = 2) +
  geom_jitter(alpha = 0.1, size = 2.5, width = 0.3, height = 0.3) +
  geom_text(aes(label = word), check_overlap = TRUE, vjust = 1.5) +
  scale_x_log10(labels = percent_format()) +
  scale_y_log10(labels = percent_format()) +
  scale_color_gradient(limits = c(0, 0.001), low = "darkslategray4", high = "gray75") +
  facet_wrap(~author, ncol = 2) +
  theme(legend.position="none") +
  labs(y = "Jane Austen", x = NULL)


cor.test(data = frequency[frequency$author == "Brontë Sisters",],
         ~ proportion + `Jane Austen`)

cor.test(data = frequency[frequency$author == "H.G. Wells",], 
         ~ proportion + `Jane Austen`)
```